"""client profile fields

Revision ID: 0167599c35af
Revises: a42c0bd505f7
Create Date: 2026-08-17 15:41:26.214308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0167599c35af'
down_revision: Union[str, Sequence[str], None] = 'a42c0bd505f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('middle_name', sa.String(length=100), nullable=True))
    op.add_column('clients', sa.Column('city_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_clients_default_city_id'), table_name='clients')
    op.create_index(op.f('ix_clients_city_id'), 'clients', ['city_id'], unique=False)
    op.drop_column('clients', 'full_name')
    op.drop_column('clients', 'default_city_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('default_city_id', sa.CHAR(length=32), nullable=True))
    op.add_column('clients', sa.Column('full_name', sa.VARCHAR(length=200), nullable=True))
    op.drop_index(op.f('ix_clients_city_id'), table_name='clients')
    op.create_index(op.f('ix_clients_default_city_id'), 'clients', ['default_city_id'], unique=False)
    op.drop_column('clients', 'city_id')
    op.drop_column('clients', 'middle_name')
    op.drop_column('clients', 'first_name')
    op.drop_column('clients', 'last_name')
    # ### end Alembic commands ###
