"""cell grid spans and status moment

Revision ID: 0e0f6aec0291
Revises: 2cc2efde0f58
Create Date: 2026-08-18 14:41:33.762409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0f6aec0291'
down_revision: Union[str, Sequence[str], None] = '2cc2efde0f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('row_span', sa.Integer(), nullable=True))
    op.add_column('cells', sa.Column('col_span', sa.Integer(), nullable=True))
    op.add_column('cells', sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cells', 'status_changed_at')
    op.drop_column('cells', 'col_span')
    op.drop_column('cells', 'row_span')
    # ### end Alembic commands ###
