"""bookings, timeline, access codes

Revision ID: 12e9e5575047
Revises: 49fa8bc984a9
Create Date: 2026-08-17 10:36:29.425325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e9e5575047'
down_revision: Union[str, Sequence[str], None] = '49fa8bc984a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('postamat_id', sa.Uuid(), nullable=False),
    sa.Column('cell_id', sa.Uuid(), nullable=False),
    sa.Column('cell_type_id', sa.Uuid(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('depositor', sa.String(length=16), nullable=False),
    sa.Column('courier_phone', sa.String(length=16), nullable=True),
    sa.Column('recipient_phone', sa.String(length=16), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deposited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_cell_id'), 'bookings', ['cell_id'], unique=False)
    op.create_index(op.f('ix_bookings_cell_type_id'), 'bookings', ['cell_type_id'], unique=False)
    op.create_index('ix_bookings_client_created', 'bookings', ['client_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    op.create_index(op.f('ix_bookings_postamat_id'), 'bookings', ['postamat_id'], unique=False)
    op.create_index(op.f('ix_bookings_recipient_phone'), 'bookings', ['recipient_phone'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index('uq_active_booking_per_cell', 'bookings', ['cell_id'], unique=True, sqlite_where=sa.text("status IN ('awaiting_deposit', 'awaiting_pickup', 'paid', 'pending_payment')"), postgresql_where=sa.text("status IN ('awaiting_deposit', 'awaiting_pickup', 'paid', 'pending_payment')"))
    op.create_table('access_codes',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_codes_booking_id'), 'access_codes', ['booking_id'], unique=False)
    op.create_index(op.f('ix_access_codes_code_hash'), 'access_codes', ['code_hash'], unique=False)
    op.create_table('booking_events',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_events_booking_id'), 'booking_events', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_events_booking_id'), table_name='booking_events')
    op.drop_table('booking_events')
    op.drop_index(op.f('ix_access_codes_code_hash'), table_name='access_codes')
    op.drop_index(op.f('ix_access_codes_booking_id'), table_name='access_codes')
    op.drop_table('access_codes')
    op.drop_index('uq_active_booking_per_cell', table_name='bookings', sqlite_where=sa.text("status IN ('awaiting_deposit', 'awaiting_pickup', 'paid', 'pending_payment')"), postgresql_where=sa.text("status IN ('awaiting_deposit', 'awaiting_pickup', 'paid', 'pending_payment')"))
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_recipient_phone'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_postamat_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.drop_index('ix_bookings_client_created', table_name='bookings')
    op.drop_index(op.f('ix_bookings_cell_type_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_cell_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
