"""client block timestamp

Revision ID: 20c05556f5d8
Revises: 39a276d82715
Create Date: 2026-08-18 13:18:20.003228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c05556f5d8'
down_revision: Union[str, Sequence[str], None] = '39a276d82715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True))
    # Accounts blocked before this column existed keep a null: inventing a moment
    # would read as a decision somebody made, and nobody did.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'blocked_at')
    # ### end Alembic commands ###
