"""payment sessions

Revision ID: 2a1ebd9ed5d4
Revises: 9b3881f58663
Create Date: 2026-08-18 12:04:40.449025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1ebd9ed5d4'
down_revision: Union[str, Sequence[str], None] = '9b3881f58663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('bank_code', sa.String(length=16), nullable=True))
    op.add_column('payments', sa.Column('redirect_url', sa.String(length=1000), nullable=True))
    op.add_column('payments', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # Existing rows were opened before a bank could be named, and every one of
    # them went through the mock. Saying so is truer than leaving them null.
    op.execute("UPDATE payments SET bank_code = provider WHERE bank_code IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'expires_at')
    op.drop_column('payments', 'redirect_url')
    op.drop_column('payments', 'bank_code')
    # ### end Alembic commands ###
