"""postamat photos

Revision ID: 33d77c9f2b74
Revises: 57b644514458
Create Date: 2026-08-17 14:53:42.900702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d77c9f2b74'
down_revision: Union[str, Sequence[str], None] = '57b644514458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postamat_photos',
    sa.Column('postamat_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=32), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['postamat_id'], ['postamats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postamat_photos_postamat_id'), 'postamat_photos', ['postamat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postamat_photos_postamat_id'), table_name='postamat_photos')
    op.drop_table('postamat_photos')
    # ### end Alembic commands ###
