"""admin user scope and last login

Revision ID: 39a276d82715
Revises: 2a1ebd9ed5d4
Create Date: 2026-08-18 13:14:22.952308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a276d82715'
down_revision: Union[str, Sequence[str], None] = '2a1ebd9ed5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default because the table is not empty, and an existing account is
    # unrestricted: an empty list means the whole fleet.
    op.add_column('admin_users', sa.Column('postamat_ids', sa.JSON(), nullable=False,
                                           server_default='[]'))
    op.add_column('admin_users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'last_login_at')
    op.drop_column('admin_users', 'postamat_ids')
    # ### end Alembic commands ###
