"""tariffs

Revision ID: 49fa8bc984a9
Revises: afb57d4e3c91
Create Date: 2026-08-17 09:28:16.319984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49fa8bc984a9'
down_revision: Union[str, Sequence[str], None] = 'afb57d4e3c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('city_id', sa.Uuid(), nullable=False),
    sa.Column('cell_type_id', sa.Uuid(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cell_type_id'], ['cell_types.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'cell_type_id', 'duration_hours', name='uq_tariff')
    )
    op.create_index(op.f('ix_tariffs_cell_type_id'), 'tariffs', ['cell_type_id'], unique=False)
    op.create_index(op.f('ix_tariffs_city_id'), 'tariffs', ['city_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tariffs_city_id'), table_name='tariffs')
    op.drop_index(op.f('ix_tariffs_cell_type_id'), table_name='tariffs')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
