"""custody

Revision ID: 57b644514458
Revises: 93ff7a72630e
Create Date: 2026-08-17 14:45:23.349384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b644514458'
down_revision: Union[str, Sequence[str], None] = '93ff7a72630e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custody_records',
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('postamat_id', sa.Uuid(), nullable=False),
    sa.Column('cell_id', sa.Uuid(), nullable=False),
    sa.Column('cell_number', sa.Integer(), nullable=False),
    sa.Column('removed_by', sa.String(length=64), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('closed_by', sa.String(length=64), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custody_records_booking_id'), 'custody_records', ['booking_id'], unique=True)
    op.create_index(op.f('ix_custody_records_cell_id'), 'custody_records', ['cell_id'], unique=False)
    op.create_index(op.f('ix_custody_records_postamat_id'), 'custody_records', ['postamat_id'], unique=False)
    op.create_index(op.f('ix_custody_records_status'), 'custody_records', ['status'], unique=False)
    op.create_table('custody_handovers',
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('to_whom', sa.String(length=16), nullable=False),
    sa.Column('by_admin', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['custody_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custody_handovers_record_id'), 'custody_handovers', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custody_handovers_record_id'), table_name='custody_handovers')
    op.drop_table('custody_handovers')
    op.drop_index(op.f('ix_custody_records_status'), table_name='custody_records')
    op.drop_index(op.f('ix_custody_records_postamat_id'), table_name='custody_records')
    op.drop_index(op.f('ix_custody_records_cell_id'), table_name='custody_records')
    op.drop_index(op.f('ix_custody_records_booking_id'), table_name='custody_records')
    op.drop_table('custody_records')
    # ### end Alembic commands ###
