"""audit trace id

Revision ID: 76a11db13286
Revises: b72cf16595d2
Create Date: 2026-08-18 14:59:00.527643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a11db13286'
down_revision: Union[str, Sequence[str], None] = 'b72cf16595d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_entries', sa.Column('trace_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_audit_entries_trace_id'), 'audit_entries', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entries_trace_id'), table_name='audit_entries')
    op.drop_column('audit_entries', 'trace_id')
    # ### end Alembic commands ###
