"""overdue statuses

Revision ID: 93ff7a72630e
Revises: e8013f4bdc62
Create Date: 2026-08-17 14:36:09.607810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ff7a72630e'
down_revision: Union[str, Sequence[str], None] = 'e8013f4bdc62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('remove_after', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Written by hand: autogenerate compares index columns, not the text of a
    # partial predicate, so it does not see that three statuses joined the set
    # that holds a cell. Without this rebuild the index still lists only four,
    # and a cell whose parcel is sitting there overdue can be sold to somebody
    # else.
    held = (
        "status IN ('awaiting_deposit', 'awaiting_pickup', 'expired', 'grace', "
        "'overdue', 'paid', 'pending_payment')"
    )
    op.drop_index('uq_active_booking_per_cell', table_name='bookings')
    op.create_index(
        'uq_active_booking_per_cell', 'bookings', ['cell_id'], unique=True,
        sqlite_where=sa.text(held), postgresql_where=sa.text(held),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminded_at')
    op.drop_column('bookings', 'remove_after')
    # ### end Alembic commands ###

    previous = (
        "status IN ('awaiting_deposit', 'awaiting_pickup', 'paid', 'pending_payment')"
    )
    op.drop_index('uq_active_booking_per_cell', table_name='bookings')
    op.create_index(
        'uq_active_booking_per_cell', 'bookings', ['cell_id'], unique=True,
        sqlite_where=sa.text(previous), postgresql_where=sa.text(previous),
    )
