"""booking payload columns

Revision ID: 9b3881f58663
Revises: b45f72c77a56
Create Date: 2026-08-18 11:57:10.686560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3881f58663'
down_revision: Union[str, Sequence[str], None] = 'b45f72c77a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pickup_code_sent_at', sa.DateTime(timezone=True), nullable=True))
    # server_default because the table is not empty: an existing booking has
    # extended its hold zero times.
    op.add_column('bookings', sa.Column('hold_extensions', sa.Integer(),
                                        nullable=False, server_default='0'))
    # Bookings created before this migration were issued all three codes at once
    # and the pickup one has been live ever since. Those grants stay valid — the
    # parcel behind that door has to remain collectable — but the purpose name
    # goes: a courier now receives the deposit code and only that.
    op.execute("UPDATE access_codes SET purpose = 'deposit' WHERE purpose = 'courier'")
    # Two rows per booking with the same purpose would be two live PINs, so the
    # duplicates that merge creates are dropped, newest kept.
    op.execute("""
        DELETE FROM access_codes WHERE id NOT IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY booking_id, purpose ORDER BY created_at DESC
                ) AS rank FROM access_codes
            ) WHERE rank = 1
        )
    """)
    op.execute(
        "UPDATE notifications SET kind = 'deposit_code' WHERE kind = 'courier_code'"
    )
    # The pickup code used to exist from booking time; for a parcel already in a
    # cell the fact that it went out is true as of the deposit.
    op.execute(
        "UPDATE bookings SET pickup_code_sent_at = deposited_at "
        "WHERE deposited_at IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE notifications SET kind = 'courier_code' WHERE kind = 'deposit_code'"
    )
    op.drop_column('bookings', 'hold_extensions')
    op.drop_column('bookings', 'pickup_code_sent_at')
    # ### end Alembic commands ###
