"""contract statuses and timeline steps

Revision ID: a42c0bd505f7
Revises: 33d77c9f2b74
Create Date: 2026-08-17 15:37:39.186735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42c0bd505f7'
down_revision: Union[str, Sequence[str], None] = '33d77c9f2b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_events', sa.Column('step', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###

    # By hand again: the held-status set gained `to_remove` and lost `paid`, and
    # autogenerate compares index columns rather than the text of a partial
    # predicate. An index still listing `paid` would let a cell be sold out from
    # under a parcel that staff have been told to pull.
    held = (
        "status IN ('awaiting_deposit', 'awaiting_pickup', 'expired', 'grace', "
        "'overdue', 'pending_payment', 'to_remove')"
    )
    op.drop_index('uq_active_booking_per_cell', table_name='bookings')
    op.create_index(
        'uq_active_booking_per_cell', 'bookings', ['cell_id'], unique=True,
        sqlite_where=sa.text(held), postgresql_where=sa.text(held),
    )

    # Rows written before this migration used a status the contract does not
    # define; there is no `paid` on the wire any more.
    op.execute(
        "UPDATE bookings SET status = 'awaiting_deposit' WHERE status = 'paid'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_events', 'step')
    # ### end Alembic commands ###

    previous = (
        "status IN ('awaiting_deposit', 'awaiting_pickup', 'expired', 'grace', "
        "'overdue', 'paid', 'pending_payment')"
    )
    op.drop_index('uq_active_booking_per_cell', table_name='bookings')
    op.create_index(
        'uq_active_booking_per_cell', 'bookings', ['cell_id'], unique=True,
        sqlite_where=sa.text(previous), postgresql_where=sa.text(previous),
    )
