"""postamat grid, working hours, blocked reason

Revision ID: a8369e271825
Revises: 76a11db13286
Create Date: 2026-08-20 16:35:02.549712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8369e271825'
down_revision: Union[str, Sequence[str], None] = '76a11db13286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postamats', sa.Column('blocked_reason', sa.String(length=500), nullable=True))
    op.add_column('postamats', sa.Column('working_hours', sa.String(length=64), nullable=True))
    op.add_column('postamats', sa.Column('grid_rows', sa.Integer(), nullable=True))
    op.add_column('postamats', sa.Column('grid_cols', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('postamats', 'grid_cols')
    op.drop_column('postamats', 'grid_rows')
    op.drop_column('postamats', 'working_hours')
    op.drop_column('postamats', 'blocked_reason')
    # ### end Alembic commands ###
