"""cells

Revision ID: afb57d4e3c91
Revises: 6d13cda6dc34
Create Date: 2026-08-17 09:26:23.744336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb57d4e3c91'
down_revision: Union[str, Sequence[str], None] = '6d13cda6dc34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cells',
    sa.Column('postamat_id', sa.Uuid(), nullable=False),
    sa.Column('cell_type_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.Column('board', sa.Integer(), nullable=False),
    sa.Column('output', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_maintenance', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cell_type_id'], ['cell_types.id'], ),
    sa.ForeignKeyConstraint(['postamat_id'], ['postamats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postamat_id', 'number', name='uq_cell_number')
    )
    op.create_index(op.f('ix_cells_cell_type_id'), 'cells', ['cell_type_id'], unique=False)
    op.create_index(op.f('ix_cells_postamat_id'), 'cells', ['postamat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cells_postamat_id'), table_name='cells')
    op.drop_index(op.f('ix_cells_cell_type_id'), table_name='cells')
    op.drop_table('cells')
    # ### end Alembic commands ###
