"""push tokens, notification settings, read_at

Revision ID: b45f72c77a56
Revises: 0167599c35af
Create Date: 2026-08-18 11:37:44.067655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45f72c77a56'
down_revision: Union[str, Sequence[str], None] = '0167599c35af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('push_parcel_deposited', sa.Boolean(), nullable=False),
    sa.Column('push_cell_opened', sa.Boolean(), nullable=False),
    sa.Column('push_expiring_soon', sa.Boolean(), nullable=False),
    sa.Column('push_marketing', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_client_id'), 'notification_settings', ['client_id'], unique=True)
    op.create_table('push_tokens',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_tokens_client_id'), 'push_tokens', ['client_id'], unique=False)
    # One row per device per client. Registration is idempotent in the service,
    # but two launches racing each other would still write two rows without this.
    op.create_index('uq_push_token_per_client', 'push_tokens', ['client_id', 'token'],
                    unique=True)
    op.add_column('notifications', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    # Carry the fact across before the column that held it goes: a notification
    # already read must not come back unread in the badge count. The exact moment
    # was never stored, so the migration's own clock is the best answer there is.
    op.execute('UPDATE notifications SET read_at = CURRENT_TIMESTAMP WHERE is_read = 1')
    op.drop_column('notifications', 'is_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.BOOLEAN(), nullable=False,
                                             server_default=sa.text('0')))
    op.execute('UPDATE notifications SET is_read = 1 WHERE read_at IS NOT NULL')
    op.drop_column('notifications', 'read_at')
    op.drop_index('uq_push_token_per_client', table_name='push_tokens')
    op.drop_index(op.f('ix_push_tokens_client_id'), table_name='push_tokens')
    op.drop_table('push_tokens')
    op.drop_index(op.f('ix_notification_settings_client_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
