"""device telemetry and provisioning

Revision ID: b72cf16595d2
Revises: 0e0f6aec0291
Create Date: 2026-08-18 14:50:29.943926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72cf16595d2'
down_revision: Union[str, Sequence[str], None] = '0e0f6aec0291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('os_version', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('certificate_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('devices', sa.Column('on_battery', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('tamper_detected', sa.Boolean(), nullable=True))
    # server_default because the table may not be empty, and a device that has
    # reported nothing has jammed nothing.
    op.add_column('devices', sa.Column('jammed_cell_ids', sa.JSON(), nullable=False,
                                       server_default='[]'))
    op.add_column('devices', sa.Column('provisioning_code_hash', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('provisioning_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'provisioning_expires_at')
    op.drop_column('devices', 'provisioning_code_hash')
    op.drop_column('devices', 'jammed_cell_ids')
    op.drop_column('devices', 'tamper_detected')
    op.drop_column('devices', 'on_battery')
    op.drop_column('devices', 'certificate_expires_at')
    op.drop_column('devices', 'os_version')
    # ### end Alembic commands ###
