"""booking event sequence

Revision ID: ed2858d11271
Revises: 12e9e5575047
Create Date: 2026-08-17 11:48:37.561287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2858d11271'
down_revision: Union[str, Sequence[str], None] = '12e9e5575047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is here for the rows that already exist: a NOT NULL column
    # added without one fails on a non-empty table. New rows get their position
    # from the application, which is the only place that knows it.
    op.add_column(
        'booking_events',
        sa.Column('seq', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_events', 'seq')
    # ### end Alembic commands ###
