"""cities and cell types

Revision ID: f1115e0c48e5
Revises: c5094fa66f11
Create Date: 2026-08-15 14:29:26.387794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1115e0c48e5'
down_revision: Union[str, Sequence[str], None] = 'c5094fa66f11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cell_types',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name_tk', sa.String(length=50), nullable=False),
    sa.Column('name_ru', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=50), nullable=False),
    sa.Column('width_cm', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('depth_cm', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cell_types_code'), 'cell_types', ['code'], unique=True)
    op.create_table('cities',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_tk', sa.String(length=100), nullable=False),
    sa.Column('name_ru', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_code'), 'cities', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_code'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_cell_types_code'), table_name='cell_types')
    op.drop_table('cell_types')
    # ### end Alembic commands ###
